"""empty message

Revision ID: 103521d895b5
Revises: 2ad20c6f3da4
Create Date: 2026-03-10 03:19:52.835677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103521d895b5'
down_revision = '2ad20c6f3da4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_ci'), type_='unique')
        batch_op.drop_column('ci')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ci', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_user_ci'), ['ci'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
