"""Add expires_at to invitations

Revision ID: 7e4cc8d1b595
Revises: 6e2496c994af
Create Date: 2026-03-30 22:46:17.443410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e4cc8d1b595'
down_revision = '6e2496c994af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend_invitation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    with op.batch_alter_table('friend_invitation', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
