"""add ci column to user table

Revision ID: a1b2c3d4e5f6
Revises: 52f6838e05c6
Create Date: 2026-03-08 12:00:00.000000
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '52f6838e05c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # add ci column as nullable first to avoid conflicts for existing rows
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('ci', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint('uq_user_ci', ['ci'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_ci', type_='unique')
        batch_op.drop_column('ci')
    # ### end Alembic commands ###
