"""Sync_and_verify

Revision ID: a45581aecb92
Revises: 
Create Date: 2026-04-20 01:49:32.043978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a45581aecb92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_group',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_expense_group'))
        batch_op.drop_index(batch_op.f('idx_expense_paid_by'))
        batch_op.drop_constraint(batch_op.f('expense_paid_by_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('expense_group_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'group', ['group_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['paid_by'], ['id'])

    with op.batch_alter_table('expense_participant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_expense_participant_expense'))
        batch_op.drop_index(batch_op.f('idx_expense_participant_user'))
        batch_op.drop_constraint(batch_op.f('expense_participant_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('expense_participant_expense_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'expense', ['expense_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('friend_invitation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_friend_invitation_inviter_id'))
        batch_op.create_index(batch_op.f('ix_friend_invitation_inviter_id'), ['inviter_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('friend_invitation_inviter_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['inviter_id'], ['id'])

    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('friendship_requester_id_addressee_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('idx_friendship_addressee'))
        batch_op.drop_index(batch_op.f('idx_friendship_requester'))
        batch_op.drop_index(batch_op.f('idx_friendship_status'))
        batch_op.create_unique_constraint('uq_friendship', ['requester_id', 'addressee_id'])
        batch_op.drop_constraint(batch_op.f('friendship_requester_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('friendship_addressee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['requester_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['addressee_id'], ['id'])

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_group_created_by'))
        batch_op.create_index(batch_op.f('ix_group_created_by'), ['created_by'], unique=False)
        batch_op.drop_constraint(batch_op.f('group_created_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])

    with op.batch_alter_table('group_member', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('group_member_group_id_user_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('idx_group_member_group'))
        batch_op.drop_index(batch_op.f('idx_group_member_user'))
        batch_op.drop_constraint(batch_op.f('group_member_group_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('group_member_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'group', ['group_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_invitation_group_id'))
        batch_op.create_index(batch_op.f('ix_invitation_group_id'), ['group_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('invitation_group_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'group', ['group_id'], ['id'])

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'manual'::character varying"))
        batch_op.drop_index(batch_op.f('idx_payment_group'))
        batch_op.drop_index(batch_op.f('idx_payment_payer'))
        batch_op.drop_index(batch_op.f('idx_payment_receiver'))
        batch_op.drop_index(batch_op.f('idx_payment_status'))
        batch_op.drop_constraint(batch_op.f('payment_payer_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('payment_receiver_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('payment_group_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['receiver_id'], ['id'])
        batch_op.create_foreign_key(None, 'group', ['group_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['payer_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('verification_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('verification_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('verification_expires_at')
        batch_op.drop_column('verification_code')
        batch_op.drop_column('is_verified')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('payment_group_id_fkey'), 'group', ['group_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('payment_receiver_id_fkey'), 'user', ['receiver_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('payment_payer_id_fkey'), 'user', ['payer_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_payment_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_payment_receiver'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_payment_payer'), ['payer_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_payment_group'), ['group_id'], unique=False)
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'manual'::character varying"))

    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('invitation_group_id_fkey'), 'group', ['group_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_invitation_group_id'))
        batch_op.create_index(batch_op.f('idx_invitation_group_id'), ['group_id'], unique=False)

    with op.batch_alter_table('group_member', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('group_member_user_id_fkey'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('group_member_group_id_fkey'), 'group', ['group_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_group_member_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_group_member_group'), ['group_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('group_member_group_id_user_id_key'), ['group_id', 'user_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('group_created_by_fkey'), 'user', ['created_by'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_group_created_by'))
        batch_op.create_index(batch_op.f('idx_group_created_by'), ['created_by'], unique=False)

    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('friendship_addressee_id_fkey'), 'user', ['addressee_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('friendship_requester_id_fkey'), 'user', ['requester_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('uq_friendship', type_='unique')
        batch_op.create_index(batch_op.f('idx_friendship_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_friendship_requester'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_friendship_addressee'), ['addressee_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('friendship_requester_id_addressee_id_key'), ['requester_id', 'addressee_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('friend_invitation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('friend_invitation_inviter_id_fkey'), 'user', ['inviter_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_friend_invitation_inviter_id'))
        batch_op.create_index(batch_op.f('idx_friend_invitation_inviter_id'), ['inviter_id'], unique=False)

    with op.batch_alter_table('expense_participant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('expense_participant_expense_id_fkey'), 'expense', ['expense_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('expense_participant_user_id_fkey'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_expense_participant_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_expense_participant_expense'), ['expense_id'], unique=False)

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('expense_group_id_fkey'), 'group', ['group_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('expense_paid_by_fkey'), 'user', ['paid_by'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_expense_paid_by'), ['paid_by'], unique=False)
        batch_op.create_index(batch_op.f('idx_expense_group'), ['group_id'], unique=False)

    op.drop_table('user_group')
    # ### end Alembic commands ###
