"""Added amount_owed to ExpenseParticipant

Revision ID: f8a99bea7b11
Revises: 4054e7faef57
Create Date: 2026-03-12 03:00:56.968139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8a99bea7b11'
down_revision = '4054e7faef57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_owed', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_participant', schema=None) as batch_op:
        batch_op.drop_column('amount_owed')

    # ### end Alembic commands ###
